export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DATA_URL = "https://fakestoreapi.com/products?limit=5";
export const SUB_QUANTITY = "SUB_QUANTITY";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const ADD_SHIPPING = "ADD_SHIPPING";
export const SUB_SHIPPING = "SUB_SHIPPING";
export const CLEAR_CART = "CLEAR_CART";
export const FETCH_DATA = "FETCH_DATA";
